### ISSUE TITLE
MTG-Art-Downloader switched to using poetry, but README still says "pip install -r requirements.txt"

### ISSUE THREAD

**Issue by HelixVita** [MrTeferi/MTG-Art-Downloader#5]
It's unclear how to how to install dependencies now that there's no "requirements.txt. file anymore.

My suggestion would be to maybe update the README with some instructions for those of us who are not familiar with Poetry?

**Comment by HelixVita** [comment]
Just saw this PR: https://github.com/MrTeferi/MTG-Art-Downloader/pull/4

Should probably merge that asap

**Comment by Investigamer** [comment]
Readme updated
